### ISSUE TITLE
Feature request: Add a getWilayaByPhoneCode method

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/leblad#18]
As a user, I would like to have a method which it returns a wilaya code for a given phone code.  
Example:
- `getWilayaByPhoneCode(41)` return `WilayaObject{ name: 'Oran'.. }`

It would be great if the method accepts full phone numbers, truncate the phone code and then return the wilaya, example:  
- `getWilayaByPhoneCode('0412345678')`

**N.B:** 

- Please read our [contributing guidelines](https://github.com/dzcode-io/leblad/blob/develop/.github/CONTRIBUTING.md) and our [code of conduct](https://github.com/dzcode-io/leblad/blob/develop/.github/CODE_OF_CONDUCT.md)
- Comment here so we know that you're on it 🐝 .
- Please keep it simple and clean, [KISS](https://en.wikipedia.org/wiki/KISS_principle) 🥰 .
- Write tests
- Update documentation in the readme file
- It's okay to submit a PR with a function that only take a phone code (not a complete phone number).
- Keep functions small, and [pure](https://www.freecodecamp.org/news/what-is-a-pure-function-in-javascript-acb887375dfe/). We may reuse your code in the future ♻️ .
- Ask for help, here or in [Slack](https://join.slack.com/t/dzcode/shared_invite/zt-ek9kscb7-m8z_~cBjX79l~uchuABPFQ).

Happy Hacking !

**Comment by AmineVolk** [comment]
@Fcmam5  i will do it

**Comment by Fcmam5** [comment]
> @Fcmam5 i will do it

@AmineVolk Great!  Happy hacking
