### ISSUE TITLE
Feature request: Add `getPhoneCodeForWilaya` and `getPhoneCodesForWilaya `

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/leblad#19]
⚠️⚠️⚠️  
**This issue is for first-timers only, we'd like you to start your open-source journey from here 😄**
⚠️⚠️⚠️

As a library consumer, I would like to have a method that returns phone codes for each wilaya.  
One of the use cases for this feature is with forms; in order to have a better user experience, we would like to set the phone code initials when the user select their wilaya. For example: if I fill the address block and set my city to Oran (code: 31) I would like if the phone number block is set automatically to 041.

What we want to add:
- A `getPhoneCodeForWilaya` function that takes one parameter (wilayaCode: number) and returns the first phone code (as a wilaya, like Algiers have two phone codes: 21, 23).
- A `getPhoneCodesForWilaya`  function that takes one parameter (wilayaCode: number) and returns an array of all phoneCodes of that wilaya.

**NB:**

- Please read our [contributing guidelines](https://github.com/dzcode-io/leblad/blob/develop/.github/CONTRIBUTING.md) and our [code of conduct](https://github.com/dzcode-io/leblad/blob/develop/.github/CODE_OF_CONDUCT.md)
- Comment here so we know that you're on it 🐝 .
- Clone this repository, read the code and try to understand how we structured it.
- Start hacking (_PS: You can check the [PRs we merged](https://github.com/dzcode-io/leblad/pulls?q=is%3Apr+is%3Amerged) and see how our smart contributors added this kind of features_)
- Update documentation in the readme file
- Ask for help, here or in [Slack](https://join.slack.com/t/dzcode/shared_invite/zt-ek9kscb7-m8z_~cBjX79l~uchuABPFQ).

Happy Hacking !

**Comment by oussamabouchikhi** [comment]
@Fcmam5 I will take `getPhoneCodeForWilaya`and `getPhoneCodesForWilaya `

**Comment by Fcmam5** [comment]
@oussamabouchikhi please check #20 , let's keep this issue for first-timers 😄

**Comment by oussamabouchikhi** [comment]
> 
> 
> @oussamabouchikhi please check #20 , let's keep this issue for first-timers 😄

No problem

**Comment by joeylnguyen** [comment]
Hi! May I contribute by taking on this issue?

**Comment by xxKeefer** [comment]
I would love to have this for my first time, if you need someone to help i think i could do this

**Comment by Fcmam5** [comment]
> Hi! May I contribute by taking on this issue?

@joeylnguyen you got it! Happy Hacktober Hacking 🎉 !

**Comment by Fcmam5** [comment]
> I would love to have this for my first time, if you need someone to help i think i could do this

@xxKeefer you can take #24 😄
