### ISSUE TITLE
Feature request: getWilayaByDairaName

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/leblad#20]
As a user, I would like to get a wilaya by a daira name.

It would be nice If I can pass either the name (In French), the name in English or in Arabic (_You can have the beautified dataset from: [algeria-api/data/WilayaList.json](https://github.com/Fcmam5/algeria-api/blob/develop/data/WilayaList.json)_).

**Examples:**

- `getWilayaByDairaName('ZIAMAH MANSOURIAH')`
- `getWilayaByDairaName('زيامة منصورية')` 

should return WilayaObject {name: "Jijel" ....}.

If the daira is not found return `undefined`.

**Comment by oussamabouchikhi** [comment]
@Fcmam5 I will take those two then
