### ISSUE TITLE
Feature request: getBaladyiatsForDaira

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/leblad#42]
Implement a new feature that takes a daira name (either in French, English or Arabic) and returns either a list of baladyiats or `null`.

- `getBaladyiatsForDaira(name: string): string`

Please, don't forget to update the documentation in the README file (check this [example PR](https://github.com/dzcode-io/leblad/pull/34/files)).

**Comment by oussamabouchikhi** [comment]
@Fcmam5 please assign me to this
