### ISSUE TITLE
Feature request: getWilayaByDairaName

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/leblad#43]
Implement a new feature: `getWilayaByDairaName`. That takes a Daira name (French, English or Arabic) and returns either the corresponding wilaya or `null`.

- `getWilayaByDairaName(name: string, projection?: string[]): WilayaObject`

Please, don't forget to update the documentation in the README file (check this [example PR](https://github.com/dzcode-io/leblad/pull/34/files)).

**Comment by joeylnguyen** [comment]
Hi, can you assign this to me?

**Comment by Fcmam5** [comment]
Sure, Happy hacking!

**Comment by joeylnguyen** [comment]
@Fcmam5, was this feature not already implemented in #20?

**Comment by Fcmam5** [comment]
@joeylnguyen it was 😞 sorry I missed that, but it was not exported from `index.js` and we missed that, please can you submit a PR to fix this?
