### ISSUE TITLE
getWilayaByBaladyiaName

### ISSUE THREAD

**Issue by Redaloukil** [dzcode-io/leblad#47]
Given a baladyia `name` or `code` ( would be more unique, because imo there is two baladya with same name and different wilaya).

**Comment by Redaloukil** [comment]
@Fcmam5 if it makes a sense for you please assign me to this issue.

**Comment by Fcmam5** [comment]
You can use `name`, I believe that it's unique. It might be a nice challenge to verify that tho

**Comment by Redaloukil** [comment]
@Fcmam5 Are you taking in count all Latin name and Arab name for getting resources by name ?

**Comment by Fcmam5** [comment]
Yes, please take [getWilayaByDairaName](https://github.com/dzcode-io/leblad/blob/develop/src/api/getWilayaByDairaName.js) as example
