### ISSUE TITLE
Update dataset

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [dzcode-io/leblad#70]
We know that the administrative division in Algeria has changed from 48 wilaya, to 58 wilaya, so it is clear that many of the data in this package are outdated.
that's why we need to update the dataset, so that whoever uses this package can see correct data that helps him in his work

**Comment by Fcmam5** [comment]
This looks like an issue that should be opened in https://github.com/Fcmam5/algeria-api, wdyt?

**Comment by abderrahmaneMustapha** [comment]
i think that we need to close this issue, because a new issue is already created in algeria-api repo  here https://github.com/Fcmam5/algeria-api/issues/61
