### ISSUE TITLE
Use of mutation testing in leblad - Help needed

### ISSUE THREAD

**Issue by belene** [dzcode-io/leblad#85]
Hello there!

My name is Ana. I noted that you use the mutation testing tool strykerjs in the project. 
I am a postdoctoral researcher at the University of Seville (Spain), and my colleagues and I are studying how mutation testing tools are used in practice. With this aim in mind, we have analysed over 3,500 public GitHub repositories using mutation testing tools, including yours! This work has recently been published in a journal paper available at https://link.springer.com/content/pdf/10.1007/s10664-022-10177-8.pdf. 

To complete this study, we are asking for your help to understand better how mutation testing is used in practice, please! We would be extremely grateful if you could contribute to this study by answering a brief survey of 21 simple questions (no more than 6 minutes). This is the link to the questionnaire https://forms.gle/FvXNrimWAsJYC1zB9.

Drop me an e-mail if you have any questions or comments (anasan@us.es). Thank you very much in advance!!

**Comment by ZibanPirate** [comment]
thank you @belene for reaching out, please join our slack workspace and ask there, we only use Github for tracking issues, your ask will reach more people on Slack I believe:

[<img src="https://img.shields.io/badge/Join%20us%20on%20Slack-@dzCode.io-yellow.svg?logo=slack">](https://join.slack.com/t/dzcode/shared_invite/zt-ek9kscb7-m8z_~cBjX79l~uchuABPFQ)

closing the issue as we move the discussion to slack.
